[workspace]
members = [
    "backend",
    "frontend",
    "shared",
    "tauri",
]

resolver = "2"

[profile.release]
opt-level = 3

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3